### ISSUE TITLE
Pretrained models?

### ISSUE THREAD

**Issue by BarqueroGerman** [yangzhao1230/TEACH#1]
Hi Yang, 

Congrats on the amazing work. I was wondering if you plan to release the pretrained models. That would be fantastic for comparing to your work.

Thanks,

German

**Comment by yangzhao1230** [comment]
Thank you for your interest in our work. I apologize for not initially maintaining the repository very well.

We provide the pretrained models here: [pretrained models link](https://drive.google.com/drive/folders/1Lrj5FEt7bFFiv_VnfoDFoQgZzfF4X6RJ?usp=sharing). The 'pretrained.zip' file contains the pretrained model and training configurations used to report metrics in our paper, while 'MotionCLIP.zip' contains the model used for evaluation.

You can use the following three commands to obtain the results for the last three rows of the experimental results table in our paper:

1. `python eval_humanml.py --model_path ./save/past_cond_hist_frame_5_mask_newdata/model000600000.pt --guidance_param 2 --inpainting_frames 0`

2. `python eval_humanml.py --model_path ./save/past_cond_hist_frame_5_mask_newdata/model000600000.pt --guidance_param 2 --inpainting_frames 2`

3. `python eval_humanml.py --model_path ./save/past_cond_hist_frame_5_mask_newdata/model000600000.pt --guidance_param 2 --composition True --inter_frames 2`

However, since I haven't had the opportunity to elaborate on the environment and data preparation (if you have run MDM and TEACH, this might not be an issue), you might encounter some problems when running the program. I apologize for this inconvenience. Please feel free to contact me if you encounter any other issues!

**Comment by BarqueroGerman** [comment]
Thank you for your fast reply! I couldn't execute any of your script due to missing variables, and functions defined differently as how they are being used in the code. Let me know if you update the repository with a working version of your code. Thanks!

**Comment by yangzhao1230** [comment]
I will let you know as soon as I make the repo a clean version. I apologize for any inconvenience this may have caused.

**Comment by yangzhao1230** [comment]
This repository has been deprecated, please refer to our clean new repository at https://github.com/yangzhao1230/newPCMDM.
